### Save data is stored at %SystemDrive%\Users\Public\Documents\uPlay\CODEX\Saves\FarCry5

[Settings]
###
### Game identifier
###
GameName=FarCry5
###
### uPlay Account ID
###
AccountId=c91c91c9-1c91-c91c-91c9-1c91c91c91c9
### 
### Name of the current player
###
UserName=PROJECT LIGHTNING
###
### Language that will be used in the game
###
Language=en-US
###
### Set uPlay connection to offline mode
###
Offline=0
###
### uPlay store connection
###
StoreConnected=1
###
### User email address
###
#Email=codex@rul.es
###
### User password
###
#Password=cARTHAGO$DELENDA#ESt
###
### Game CD Key
###
#CdKey=1337-1337-1337-1337
###
### uPlay auth ticket
###
#UplayTicket=BaRbATeNuSsApIeNtES
###
### Retrieve all the chunks
###
RetrieveChunks=1
###
### Blacklist as it is
###
#Blacklist=UbisoftGameLauncher.exe
###
### Enable/disable external saves converter
###
ConverterEnabled=1
###

[DLC]
###
### Automatically unlock all DLCs
###
DLCUnlockall=true
###
### Identifiers for DLCs
###
#ID=true/false
###

[SaveConverter]
###
### Game identifier
###
GameId=4311
### 
### Name of the converted profile
###
ProfileName=CPY
###