-- Banzai Escape 2: Subterranean
-- AppID: 1758950
-- Generated: 2026-08-19 18:51:38
-- Generated by https://ManifestHub.uk
-- for any kind of help join our discord

addappid(1758950)

addappid(1758951, 1, "3651e588ed8ac682488b7648d77031600a182166827ae7b4edb91e5fe8e2e024")
setManifestid(1758951, "2931143248138277844")

