-- Yi Xian: The Cultivation Card Game
-- AppID: 1948800
-- Generated: 2026-08-19 18:48:59
-- Generated by https://ManifestHub.uk
-- for any kind of help join our discord

addappid(1948800)

addappid(1948801, 1, "36faa07f73256bab7c712cb6f5d353eb2fda66998700a7fa29f504f0144bf81b")
setManifestid(1948801, "270214714667596223")

