--this is generated by https://steamtools.manifesthub.uk
addappid(4595400) --erotic clicker
addappid(4595401, 0, "e6049fa1b8bb7fde3384d861b771a48c50003f08bc6fda9995316e435fb61503")
setManifestid(4242291, "7105512903958460422")
--this is generated by https://steamtools.pages.dev
--discord  https://discord.gg/Xx2qdXCvKY
--Telegram: @manifesthab
