-- 33 Immortals
-- AppID: 958520
-- Generated: 2026-08-19 18:49:46
-- Generated by https://ManifestHub.uk
-- for any kind of help join our discord

addappid(958520)

addappid(958521, 1, "3b3e825494da5eba01605e1254ce18163cd4c7553d18ac5ade63a4c629185faa")
setManifestid(958521, "1205281432601096725")

